---
- name: Include OS specific vars
  include_vars: "{{ item }}.yml"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
      paths:
        - "{{ role_path }}/vars"

# TODO: Add distro repos

- name: Install podman packages
  package:
    name: "{{ item }}"
    state: present
  with_items: '{{ podman_packages | default(["podman"]) }}'